Repository ricardoprins/stockinator, pull requests merged in 2021-01, with the labels that each got.

#36 CONTRIBUTION FILE AND CODE OF CONDUCT
  CODE_OF_CONDUCT.md
  CONTRIBUTION.md
  README.md
Labels: DWOC, Level-1

#38 added the data_options feature
  backend/fastAPI/fastAPI.py
Labels: DWOC, Level-4

#39 Add CONTRIBUTORS.md
  CONTRIBUTORS.md
  README.md
Labels: DWOC, Level-1

#47 Add Template for Issues
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/proposal.md
Labels: DWOC, Level-1

#50 Integrate Welcome and Greeting Bot
  .github/config.yml
Labels: DWOC, Level-2

#52 Add contributors table in README.md
  README.md
Labels: DWOC, Level-1

#53 README FILE BADGES
  README.md
Labels: DWOC, Level-1
